"""Short ExtractNet smoke using the SegNet smoke checkpoint and smoke dataset."""

from __future__ import annotations

import argparse
import importlib
import json
import random
import time
from pathlib import Path
from typing import Any


DEFAULT_OUTPUT_DIR = (
    Path("offline_stroke_recovery_mvp")
    / "outputs"
    / "stroke_extraction_extractnet_smoke"
)
DEFAULT_ALLOWED_OUTPUT_ROOT = Path("offline_stroke_recovery_mvp") / "outputs"
DEFAULT_DATASET_DIR = (
    Path("offline_stroke_recovery_mvp")
    / "outputs"
    / "stroke_extraction_training_smoke"
    / "dataset_forSegNet_ExtractNet_RHSEDB_smoke"
)
DEFAULT_SEGNET_CHECKPOINT = (
    Path("offline_stroke_recovery_mvp")
    / "outputs"
    / "stroke_extraction_segnet_smoke"
    / "model"
    / "model.pth"
)


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--repo",
        type=Path,
        default=Path("external_repos") / "StrokeExtraction",
        help="Path to the external StrokeExtraction checkout.",
    )
    parser.add_argument(
        "--dataset-dir",
        type=Path,
        default=DEFAULT_DATASET_DIR,
        help="Path to the limited intermediate dataset generated by the SDNet smoke.",
    )
    parser.add_argument(
        "--segnet-checkpoint",
        type=Path,
        default=DEFAULT_SEGNET_CHECKPOINT,
        help="Path to the SegNet smoke checkpoint.",
    )
    parser.add_argument("--batch-size", type=int, default=2)
    parser.add_argument("--max-steps", type=int, default=2)
    parser.add_argument("--learning-rate", type=float, default=0.0001)
    parser.add_argument("--seed", type=int, default=123)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument(
        "--report",
        type=Path,
        default=None,
        help="JSON report path. Defaults to <output-dir>/extractnet_smoke_report.json.",
    )
    return parser


def write_report(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def main() -> int:
    args = build_arg_parser().parse_args()
    payload = run_extractnet_smoke(
        args.repo,
        dataset_dir=args.dataset_dir,
        segnet_checkpoint=args.segnet_checkpoint,
        output_dir=args.output_dir,
        batch_size=args.batch_size,
        max_steps=args.max_steps,
        learning_rate=args.learning_rate,
        seed=args.seed,
    )
    report_path = args.report or (args.output_dir / "extractnet_smoke_report.json")
    write_report(report_path, payload)
    print(json.dumps(payload, ensure_ascii=False, indent=2))
    return 0 if payload["status"] == "ok" else 1


def run_extractnet_smoke(
    repo_dir: Path,
    *,
    dataset_dir: Path,
    segnet_checkpoint: Path,
    output_dir: Path,
    batch_size: int,
    max_steps: int,
    learning_rate: float,
    seed: int,
) -> dict[str, Any]:
    stage = "extractnet_training_smoke"
    repo_dir = Path(repo_dir)
    dataset_dir = Path(dataset_dir)
    segnet_checkpoint = Path(segnet_checkpoint)
    output_dir = Path(output_dir)
    required_paths = [
        repo_dir,
        repo_dir / "model",
        dataset_dir,
        dataset_dir / "train",
        dataset_dir / "test",
        segnet_checkpoint,
    ]
    missing = [str(path) for path in required_paths if not path.exists()]
    if missing:
        return {"status": "missing_required_paths", "stage": stage, "missing": missing}

    if not _is_within_output_root(output_dir, DEFAULT_ALLOWED_OUTPUT_ROOT):
        return {
            "status": "invalid_output_dir",
            "stage": stage,
            "output_dir": str(output_dir),
            "allowed_root": str(DEFAULT_ALLOWED_OUTPUT_ROOT),
        }

    if batch_size <= 1 or max_steps <= 0 or learning_rate <= 0:
        return {
            "status": "invalid_args",
            "stage": stage,
            "args": {
                "batch_size": batch_size,
                "max_steps": max_steps,
                "learning_rate": learning_rate,
            },
        }

    import sys

    import numpy as np

    missing_modules = find_missing_modules([
        "torch",
        "torchvision",
        "scipy",
        "pandas",
        "matplotlib",
        "cv2",
    ])
    if missing_modules:
        return {
            "status": "missing_python_dependencies",
            "stage": stage,
            "missing_modules": missing_modules,
        }

    import torch
    import torch.nn.functional as F
    import torch.optim as optim
    import torch.utils.data as data
    from torchvision.transforms import Resize

    if not hasattr(np, "float"):
        np.float = float  # type: ignore[attr-defined]
    if not hasattr(np, "int"):
        np.int = int  # type: ignore[attr-defined]

    if str(repo_dir) not in sys.path:
        sys.path.insert(0, str(repo_dir))
    if not torch.cuda.is_available():
        return {"status": "cuda_unavailable", "stage": stage, "environment": _environment(torch)}

    from load_data_for_SegNetExtractNet import SegNetExtractNetLoader
    from model.model_of_ExtractNet import ExtractNet
    from model.model_of_SegNet import SegNet
    from utils import apply_stroke_t, random_colors, save_picture, seg_colors, apply_stroke
    from utils_loss_val import get_iou_with_matching

    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

    device = torch.device("cuda")
    torch.backends.cudnn.benchmark = True

    train_dataset = SegNetExtractNetLoader(is_training=True, dataset_path=str(dataset_dir), is_single=True)
    test_dataset = SegNetExtractNetLoader(is_training=False, dataset_path=str(dataset_dir), is_single=True)
    train_samples = [train_dataset[i] for i in range(len(train_dataset))]
    test_samples = [test_dataset[i] for i in range(len(test_dataset))]
    if not train_samples or not test_samples:
        return {
            "status": "no_dataset_samples",
            "stage": stage,
            "dataset": {
                "path": str(dataset_dir),
                "train_sample_count": len(train_samples),
                "test_sample_count": len(test_samples),
            },
        }

    output_dir.mkdir(parents=True, exist_ok=True)
    model_dir = output_dir / "model"
    review_dir = output_dir / "review"
    metadata_dir = output_dir / "metadata"
    model_dir.mkdir(parents=True, exist_ok=True)
    review_dir.mkdir(parents=True, exist_ok=True)
    metadata_dir.mkdir(parents=True, exist_ok=True)

    seg_net = SegNet(out_feature=True).to(device)
    seg_state = torch.load(segnet_checkpoint, map_location=device)
    seg_net.load_state_dict(seg_state["net"])
    seg_net.eval().requires_grad_(False)

    extract_net = ExtractNet().to(device).train()
    optimizer = optim.Adam(extract_net.parameters(), lr=learning_rate, betas=(0.5, 0.999))

    torch.cuda.empty_cache()
    torch.cuda.reset_peak_memory_stats()
    start = time.perf_counter()
    pool = _SmokeDataPool()
    steps: list[dict[str, Any]] = []

    max_cycles = max(1, max_steps)
    for cycle_index in range(max_cycles):
        for sample_index, sample in enumerate(train_samples, start=1):
            if len(steps) >= max_steps:
                break
            with torch.no_grad():
                batch = _prepare_extract_batch(
                    sample,
                    seg_net=seg_net,
                    device=device,
                    resize=Resize([256, 256]),
                )
            pool.add(*batch)
            while pool.data_num >= batch_size and len(steps) < max_steps:
                batch_items = pool.next(batch_size)
                step_start = time.perf_counter()
                optimizer.zero_grad(set_to_none=True)
                extract_out = extract_net(
                    batch_items[1],
                    batch_items[3],
                    batch_items[2],
                    batch_items[0],
                    batch_items[4],
                )
                loss = F.binary_cross_entropy(torch.sigmoid(extract_out), batch_items[5])
                extract_result = (torch.sigmoid(extract_out).detach() > 0.5)
                restored_extract, restored_label = _restore_strokes(
                    extract_result,
                    batch_items[5],
                    batch_items[6],
                )
                m_iou_m = get_iou_with_matching(restored_extract, restored_label)
                loss.backward()
                optimizer.step()
                torch.cuda.synchronize()
                steps.append(
                    {
                        "step": len(steps) + 1,
                        "cycle_index": cycle_index + 1,
                        "sample_index": sample_index,
                        "seconds": round(time.perf_counter() - step_start, 4),
                        "loss": float(loss.detach().cpu()),
                        "mIOUm": float(m_iou_m),
                        "max_memory_allocated_mib": _max_memory_mib(torch),
                    }
                )
        if len(steps) >= max_steps:
            break

    checkpoint_path = model_dir / "model_extract.pth"
    torch.save(
        {
            "net": extract_net.state_dict(),
            "start_step": len(steps),
            "source": "offline_stroke_recovery_mvp.stroke_extraction_extractnet_smoke",
        },
        checkpoint_path,
    )

    train_review_path = review_dir / "extractnet_train_review.png"
    test_review_path = review_dir / "extractnet_test_review.png"
    _render_review_sample(
        "train",
        train_samples[0],
        seg_net=seg_net,
        extract_net=extract_net,
        device=device,
        resize=Resize([256, 256]),
        output_path=train_review_path,
        random_colors_fn=random_colors,
        apply_stroke_t_fn=apply_stroke_t,
        apply_stroke_fn=apply_stroke,
        seg_colors=seg_colors,
    )
    _render_review_sample(
        "test",
        test_samples[0],
        seg_net=seg_net,
        extract_net=extract_net,
        device=device,
        resize=Resize([256, 256]),
        output_path=test_review_path,
        random_colors_fn=random_colors,
        apply_stroke_t_fn=apply_stroke_t,
        apply_stroke_fn=apply_stroke,
        seg_colors=seg_colors,
    )

    metadata_path = metadata_dir / "extractnet_smoke_metadata.json"
    write_report(
        metadata_path,
        {
            "source": "stroke_extraction_extractnet_smoke",
            "dataset": str(dataset_dir),
            "train_sample_count": len(train_samples),
            "test_sample_count": len(test_samples),
            "review_paths": {
                "train": str(train_review_path),
                "test": str(test_review_path),
            },
            "steps": steps,
        },
    )

    return {
        "status": "ok" if len(steps) == max_steps else "no_steps_completed",
        "stage": stage,
        "environment": _environment(torch),
        "dataset": {
            "path": str(dataset_dir),
            "train_sample_count": len(train_samples),
            "test_sample_count": len(test_samples),
        },
        "args": {
            "batch_size": batch_size,
            "max_steps": max_steps,
            "learning_rate": learning_rate,
            "seed": seed,
        },
        "completed_steps": len(steps),
        "total_seconds": round(time.perf_counter() - start, 4),
        "max_memory_allocated_mib": _max_memory_mib(torch),
        "checkpoint_path": str(checkpoint_path),
        "review_paths": {
            "train": str(train_review_path),
            "test": str(test_review_path),
        },
        "metadata_path": str(metadata_path),
        "steps": steps,
    }


def _prepare_extract_batch(
    sample: dict[str, Any],
    *,
    seg_net: Any,
    device: Any,
    resize: Any,
) -> list[Any]:
    import numpy as np
    import torch
    import torch.nn.functional as F

    reference_color = torch.from_numpy(sample["reference_color"]).unsqueeze(0).float().to(device)
    reference_segment_transformation_data = torch.from_numpy(sample["reference_segment_transformation_data"]).unsqueeze(0).float().to(device)
    target_data = torch.from_numpy(sample["target_data"]).unsqueeze(0).float().to(device)
    target_single_stroke = torch.from_numpy(sample["target_single_stroke"]).unsqueeze(0).float().to(device)
    reference_transformed_single = torch.from_numpy(sample["reference_transformed_single"]).unsqueeze(0).float().to(device)
    seg_index = torch.from_numpy(sample["seg_id"]).long().to(device)

    seg_out, seg_out_feature = seg_net(target_data, reference_color)
    return _build_extract_training_pack(
        reference_transformed_single,
        target_single_stroke,
        seg_index,
        seg_out,
        reference_segment_transformation_data,
        target_data,
        seg_out_feature,
        resize=resize,
    )


def _build_extract_training_pack(
    reference_transformed_single: Any,
    target_single_stroke: Any,
    seg_index: Any,
    seg_out: Any,
    reference_segment_transformation_data: Any,
    target_data: Any,
    seg_out_feature: Any,
    *,
    resize: Any,
) -> list[Any]:
    import numpy as np
    import torch
    import torch.nn.functional as F

    kaiti_tran_single_image = torch.reshape(reference_transformed_single, shape=(-1, 1, 256, 256))
    style_single_image = torch.reshape(target_single_stroke, shape=(-1, 1, 256, 256))
    kaiti_trans_stage2_in = []
    kaiti_trans_seg_stage2_in = []
    style_stage2_in = []
    seg_out_stage_in = []
    style_original_stage2_in = []
    cut_box_list = []
    for index in range(int(seg_index.size(0))):
        id_ = int(seg_index[index])
        id_7 = seg_label_to7(id_)
        kaiti_single_image_trans = kaiti_tran_single_image[index:index + 1]
        kaiti_image__ = np.squeeze(kaiti_single_image_trans.to("cpu").numpy())
        cut_box = _get_cut_region(kaiti_image__)
        y_t, y_b, x_l, x_r = cut_box
        cut_box_list.append(cut_box)

        kaiti_tran_in = kaiti_single_image_trans.detach()
        kaiti_tran_in = resize(kaiti_tran_in[:, :, y_t:y_b, x_l:x_r])
        kaiti_tran_in = _create_color_image(kaiti_tran_in, id_)
        kaiti_trans_stage2_in.append(kaiti_tran_in.float())

        style_in = torch.unsqueeze(style_single_image[index], dim=0).float()
        style_in = resize(style_in[:, :, y_t:y_b, x_l:x_r])
        style_stage2_in.append(style_in)

        seg_out_in = torch.sigmoid(seg_out[:, id_7:id_7 + 1]).detach().float()
        seg_out_in = resize(seg_out_in[:, :, y_t:y_b, x_l:x_r])
        seg_out_stage_in.append(seg_out_in)

        kaiti_seg_in = reference_segment_transformation_data[:, id_7:id_7 + 1].detach().float()
        kaiti_seg_in = resize(kaiti_seg_in[:, :, y_t:y_b, x_l:x_r])
        kaiti_trans_seg_stage2_in.append(kaiti_seg_in)

        style_image_original_in = resize(target_data[:, :, y_t:y_b, x_l:x_r])
        style_original_stage2_in.append(style_image_original_in)

    reference_stroke_transformation_data = torch.cat(kaiti_trans_stage2_in, dim=0)
    label = torch.cat(style_stage2_in, dim=0)
    segment_data = torch.cat(seg_out_stage_in, dim=0)
    segNet_feature = seg_out_feature["out_64_32"].repeat(label.size(0), 1, 1, 1)
    target_data = torch.cat(style_original_stage2_in, dim=0)
    reference_segment_transformation_data = torch.cat(kaiti_trans_seg_stage2_in, dim=0)
    return [
        target_data,
        reference_stroke_transformation_data,
        segment_data,
        reference_segment_transformation_data,
        segNet_feature,
        label,
        cut_box_list,
    ]


def _render_review_sample(
    split_name: str,
    sample: dict[str, Any],
    *,
    seg_net: Any,
    extract_net: Any,
    device: Any,
    resize: Any,
    output_path: Path,
    random_colors_fn: Any,
    apply_stroke_t_fn: Any,
    apply_stroke_fn: Any,
    seg_colors: Any,
) -> None:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import numpy as np
    import torch
    import torch.nn.functional as F

    with torch.no_grad():
        batch = _prepare_extract_batch(sample, seg_net=seg_net, device=device, resize=resize)
        extract_out = extract_net(batch[1], batch[3], batch[2], batch[0], batch[4])
        extract_result = (torch.sigmoid(extract_out).detach() > 0.5)
        restored_extract, restored_label = _restore_strokes(extract_result, batch[5], batch[6])
        target_rgb = sample["target_data"].transpose(1, 2, 0)
        label_show = target_rgb.copy()
        pred_show = target_rgb.copy()
        colors = random_colors_fn(len(restored_extract))
        random.shuffle(colors)
        for i in range(len(restored_extract)):
            label_show = apply_stroke_t_fn(label_show, restored_label[i] > 0.5, colors[i])
            pred_show = apply_stroke_t_fn(pred_show, restored_extract[i] > 0.5, colors[i])
        ref_show = np.transpose(sample["reference_color"], (1, 2, 0))
        fig, axes = plt.subplots(1, 4, figsize=(16, 4))
        panels = [
            ("target", target_rgb),
            ("reference_color", ref_show),
            ("label", label_show),
            ("pred", pred_show),
        ]
        for ax, (title, image) in zip(axes, panels):
            ax.imshow(np.clip(image, 0, 1))
            ax.set_title(f"{split_name}: {title}")
            ax.axis("off")
        fig.tight_layout()
        fig.savefig(output_path, dpi=150, bbox_inches="tight")
        plt.close(fig)


class _SmokeDataPool:
    def __init__(self) -> None:
        self.data_num = 0
        self.pool_data: dict[str, Any] = {}

    def add(
        self,
        target_data: Any,
        reference_stroke_transformation_data: Any,
        segment_data: Any,
        reference_segment_transformation_data: Any,
        segNet_feature: Any,
        label: Any,
        cut_box_list: list[list[int]],
    ) -> None:
        self.pool_data["target_data"] = (
            target_data
            if "target_data" not in self.pool_data
            else torch_cat(self.pool_data["target_data"], target_data)
        )
        self.pool_data["reference_stroke_transformation_data"] = (
            reference_stroke_transformation_data
            if "reference_stroke_transformation_data" not in self.pool_data
            else torch_cat(self.pool_data["reference_stroke_transformation_data"], reference_stroke_transformation_data)
        )
        self.pool_data["segment_data"] = (
            segment_data
            if "segment_data" not in self.pool_data
            else torch_cat(self.pool_data["segment_data"], segment_data)
        )
        self.pool_data["reference_segment_transformation_data"] = (
            reference_segment_transformation_data
            if "reference_segment_transformation_data" not in self.pool_data
            else torch_cat(self.pool_data["reference_segment_transformation_data"], reference_segment_transformation_data)
        )
        self.pool_data["segNet_feature"] = (
            segNet_feature
            if "segNet_feature" not in self.pool_data
            else torch_cat(self.pool_data["segNet_feature"], segNet_feature)
        )
        self.pool_data["label"] = (
            label if "label" not in self.pool_data else torch_cat(self.pool_data["label"], label)
        )
        self.pool_data["cut_box_list"] = (
            cut_box_list
            if "cut_box_list" not in self.pool_data
            else self.pool_data["cut_box_list"] + cut_box_list
        )
        self.data_num += int(label.size(0))

    def next(self, num: int) -> list[Any]:
        target_data_batch = self.pool_data["target_data"][:num]
        self.pool_data["target_data"] = self.pool_data["target_data"][num:]
        reference_stroke_transformation_data_batch = self.pool_data["reference_stroke_transformation_data"][:num]
        self.pool_data["reference_stroke_transformation_data"] = self.pool_data["reference_stroke_transformation_data"][num:]
        segment_data_batch = self.pool_data["segment_data"][:num]
        self.pool_data["segment_data"] = self.pool_data["segment_data"][num:]
        reference_segment_transformation_data_batch = self.pool_data["reference_segment_transformation_data"][:num]
        self.pool_data["reference_segment_transformation_data"] = self.pool_data["reference_segment_transformation_data"][num:]
        segNet_feature_batch = self.pool_data["segNet_feature"][:num]
        self.pool_data["segNet_feature"] = self.pool_data["segNet_feature"][num:]
        label_batch = self.pool_data["label"][:num]
        self.pool_data["label"] = self.pool_data["label"][num:]
        cut_list_batch = self.pool_data["cut_box_list"][:num]
        self.pool_data["cut_box_list"] = self.pool_data["cut_box_list"][num:]
        self.data_num -= num
        return [
            target_data_batch,
            reference_stroke_transformation_data_batch,
            segment_data_batch,
            reference_segment_transformation_data_batch,
            segNet_feature_batch,
            label_batch,
            cut_list_batch,
        ]


def _restore_strokes(out: Any, label: Any, cut_box_list: list[list[int]]) -> tuple[list[Any], list[Any]]:
    import cv2
    import numpy as np

    out = out.squeeze(1).to("cpu").numpy()
    label = label.squeeze(1).to("cpu").numpy()
    out_re = []
    label_re = []
    for i in range(len(cut_box_list)):
        y_t, y_b, x_l, x_r = cut_box_list[i]
        img = np.zeros_like(out[i])
        img[y_t:y_b, x_l:x_r] = cv2.resize(out[i].astype(np.uint8), dsize=(x_r - x_l, y_b - y_t))
        out_re.append(img)
        img_r = np.zeros_like(label[i])
        img_r[y_t:y_b, x_l:x_r] = cv2.resize(label[i].astype(np.uint8), dsize=(x_r - x_l, y_b - y_t))
        label_re.append(img_r)
    return out_re, label_re


def _get_cut_region(kaiti_imagae: Any) -> list[int]:
    import numpy as np

    if np.sum(kaiti_imagae) > 5:
        points = np.where(kaiti_imagae > 0.5)
        x_l = np.min(points[1])
        x_r = np.max(points[1])
        y_t = np.min(points[0])
        y_b = np.max(points[0])
    else:
        y_t = 0
        y_b = 255
        x_l = 0
        x_r = 255
    w = x_r - x_l + 1
    h = y_b - y_t + 1
    center_x = int((x_l + x_r) / 2)
    center_y = int((y_t + y_b) / 2)
    size = max(w, h)
    if size > 32:
        return [0, 256, 0, 256]
    elif size > 16:
        cut_size = 128
    else:
        cut_size = 64

    if center_x - cut_size / 2 <= 0:
        x_l = 0
        x_r = cut_size
    elif center_x + cut_size / 2 >= 256:
        x_l = 256 - cut_size
        x_r = 256
    else:
        x_l = int(center_x - cut_size / 2)
        x_r = x_l + cut_size

    if center_y - cut_size / 2 <= 0:
        y_t = 0
        y_b = cut_size
    elif center_y + cut_size / 2 >= 256:
        y_t = 256 - cut_size
        y_b = 256
    else:
        y_t = int(center_y - cut_size / 2)
        y_b = y_t + cut_size

    return [y_t, y_b, x_l, x_r]


def _create_color_image(image: Any, stroke_id: int) -> Any:
    import numpy as np
    import torch

    from utils import seg_colors

    image = image.repeat(1, 3, 1, 1)
    color = torch.from_numpy(np.array(seg_colors[stroke_id]).reshape(1, 3, 1, 1)).cuda()
    return image * color


def _environment(torch_module: Any) -> dict[str, Any]:
    return {
        "torch_version": torch_module.__version__,
        "cuda_available": torch_module.cuda.is_available(),
        "device_name": torch_module.cuda.get_device_name(0) if torch_module.cuda.is_available() else "",
        "cuda_runtime": getattr(torch_module.version, "cuda", None),
    }


def _max_memory_mib(torch_module: Any) -> int:
    return int(round(torch_module.cuda.max_memory_allocated() / 1024 / 1024))


def _is_within_output_root(path: Path, root: Path) -> bool:
    path_parts = Path(path).parts
    root_parts = Path(root).parts
    return len(path_parts) >= len(root_parts) and path_parts[: len(root_parts)] == root_parts


def find_missing_modules(module_names: list[str]) -> list[str]:
    missing: list[str] = []
    for module_name in module_names:
        try:
            importlib.import_module(module_name)
        except ModuleNotFoundError:
            missing.append(module_name)
    return missing


def seg_label_to7(id_: int) -> int:
    from utils import seg_label_to7 as upstream_seg_label_to7

    return upstream_seg_label_to7(id_)


def torch_cat(a: Any, b: Any) -> Any:
    import torch

    return torch.cat([a, b], dim=0)


if __name__ == "__main__":
    raise SystemExit(main())
