"""Short SegNet smoke using the generated limited intermediate dataset."""

from __future__ import annotations

import argparse
import importlib
import json
import random
import time
from pathlib import Path
from typing import Any


DEFAULT_OUTPUT_DIR = (
    Path("offline_stroke_recovery_mvp")
    / "outputs"
    / "stroke_extraction_segnet_smoke"
)
DEFAULT_ALLOWED_OUTPUT_ROOT = Path("offline_stroke_recovery_mvp") / "outputs"
DEFAULT_DATASET_DIR = (
    Path("offline_stroke_recovery_mvp")
    / "outputs"
    / "stroke_extraction_training_smoke"
    / "dataset_forSegNet_ExtractNet_RHSEDB_smoke"
)


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--repo",
        type=Path,
        default=Path("external_repos") / "StrokeExtraction",
        help="Path to the external StrokeExtraction checkout.",
    )
    parser.add_argument(
        "--dataset-dir",
        type=Path,
        default=DEFAULT_DATASET_DIR,
        help="Path to the limited intermediate dataset generated by the SDNet smoke.",
    )
    parser.add_argument("--batch-size", type=int, default=2)
    parser.add_argument("--max-steps", type=int, default=2)
    parser.add_argument("--learning-rate", type=float, default=0.0001)
    parser.add_argument("--seed", type=int, default=123)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument(
        "--report",
        type=Path,
        default=None,
        help="JSON report path. Defaults to <output-dir>/segnet_smoke_report.json.",
    )
    return parser


def write_report(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def main() -> int:
    args = build_arg_parser().parse_args()
    payload = run_segnet_smoke(
        args.repo,
        dataset_dir=args.dataset_dir,
        output_dir=args.output_dir,
        batch_size=args.batch_size,
        max_steps=args.max_steps,
        learning_rate=args.learning_rate,
        seed=args.seed,
    )
    report_path = args.report or (args.output_dir / "segnet_smoke_report.json")
    write_report(report_path, payload)
    print(json.dumps(payload, ensure_ascii=False, indent=2))
    return 0 if payload["status"] == "ok" else 1


def run_segnet_smoke(
    repo_dir: Path,
    *,
    dataset_dir: Path,
    output_dir: Path,
    batch_size: int,
    max_steps: int,
    learning_rate: float,
    seed: int,
) -> dict[str, Any]:
    stage = "segnet_training_smoke"
    repo_dir = Path(repo_dir)
    dataset_dir = Path(dataset_dir)
    output_dir = Path(output_dir)
    required_paths = [
        repo_dir,
        repo_dir / "model",
        dataset_dir,
        dataset_dir / "train",
        dataset_dir / "test",
    ]
    missing = [str(path) for path in required_paths if not path.exists()]
    if missing:
        return {"status": "missing_required_paths", "stage": stage, "missing": missing}

    if not _is_within_output_root(output_dir, DEFAULT_ALLOWED_OUTPUT_ROOT):
        return {
            "status": "invalid_output_dir",
            "stage": stage,
            "output_dir": str(output_dir),
            "allowed_root": str(DEFAULT_ALLOWED_OUTPUT_ROOT),
        }

    if batch_size <= 1 or max_steps <= 0 or learning_rate <= 0:
        return {
            "status": "invalid_args",
            "stage": stage,
            "args": {
                "batch_size": batch_size,
                "max_steps": max_steps,
                "learning_rate": learning_rate,
            },
        }

    import sys

    import numpy as np
    missing_modules = find_missing_modules(["torch", "scipy", "pandas", "matplotlib"])
    if missing_modules:
        return {
            "status": "missing_python_dependencies",
            "stage": stage,
            "missing_modules": missing_modules,
        }

    import torch
    import torch.nn.functional as F
    import torch.optim as optim
    import torch.utils.data as data

    if not hasattr(np, "float"):
        np.float = float  # type: ignore[attr-defined]
    if not hasattr(np, "int"):
        np.int = int  # type: ignore[attr-defined]

    if str(repo_dir) not in sys.path:
        sys.path.insert(0, str(repo_dir))
    if not torch.cuda.is_available():
        return {"status": "cuda_unavailable", "stage": stage, "environment": _environment(torch)}

    from load_data_for_SegNetExtractNet import SegNetExtractNetLoader
    from model.model_of_SegNet import SegNet
    from utils_loss_val import get_mean_IOU

    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

    device = torch.device("cuda")
    torch.backends.cudnn.benchmark = True
    train_dataset = SegNetExtractNetLoader(is_training=True, dataset_path=str(dataset_dir))
    train_loader = data.DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=0)

    output_dir.mkdir(parents=True, exist_ok=True)
    model_dir = output_dir / "model"
    model_dir.mkdir(parents=True, exist_ok=True)

    seg_net = SegNet(out_feature=False).to(device).train()
    optimizer = optim.Adam(seg_net.parameters(), lr=learning_rate, betas=(0.5, 0.999))
    cached_batches = [batch_sample for batch_sample in train_loader if batch_sample["target_data"].size(0) == batch_size]
    if not cached_batches:
        return {
            "status": "no_full_batches",
            "stage": stage,
            "dataset": {"path": str(dataset_dir), "train_sample_count": len(train_dataset)},
            "args": {
                "batch_size": batch_size,
                "max_steps": max_steps,
                "learning_rate": learning_rate,
                "seed": seed,
            },
        }

    torch.cuda.empty_cache()
    torch.cuda.reset_peak_memory_stats()
    start = time.perf_counter()
    steps: list[dict[str, Any]] = []
    for step_number, batch_index in plan_smoke_schedule(full_batches=len(cached_batches), max_steps=max_steps):
        batch_sample = cached_batches[batch_index - 1]
        step_start = time.perf_counter()
        optimizer.zero_grad(set_to_none=True)
        reference_color = batch_sample["reference_color"].float().to(device)
        label_seg = batch_sample["label_seg"].float().to(device)
        target_data = batch_sample["target_data"].float().to(device)

        seg_out = seg_net(target_data, reference_color)
        seg_prob = torch.sigmoid(seg_out)
        seg_loss = F.binary_cross_entropy(seg_prob, label_seg)
        seg_result = (seg_prob.detach() > 0.5)
        mean_iou = get_mean_IOU(seg_result, label_seg)
        seg_loss.backward()
        optimizer.step()
        torch.cuda.synchronize()

        steps.append(
            {
                "step": step_number,
                "batch_index": batch_index,
                "seconds": round(time.perf_counter() - step_start, 4),
                "seg_loss": float(seg_loss.detach().cpu()),
                "mean_iou": float(mean_iou.detach().cpu()),
                "max_memory_allocated_mib": _max_memory_mib(torch),
            }
        )

    checkpoint_path = model_dir / "model.pth"
    torch.save(
        {
            "net": seg_net.state_dict(),
            "start_step": len(steps),
            "source": "offline_stroke_recovery_mvp.stroke_extraction_segnet_smoke",
        },
        checkpoint_path,
    )

    return {
        "status": "ok" if len(steps) == max_steps else "no_steps_completed",
        "stage": stage,
        "environment": _environment(torch),
        "dataset": {
            "path": str(dataset_dir),
            "train_sample_count": len(train_dataset),
        },
        "args": {
            "batch_size": batch_size,
            "max_steps": max_steps,
            "learning_rate": learning_rate,
            "seed": seed,
        },
        "completed_steps": len(steps),
        "total_seconds": round(time.perf_counter() - start, 4),
        "max_memory_allocated_mib": _max_memory_mib(torch),
        "checkpoint_path": str(checkpoint_path),
        "steps": steps,
    }


def _environment(torch_module: Any) -> dict[str, Any]:
    return {
        "torch_version": torch_module.__version__,
        "cuda_available": torch_module.cuda.is_available(),
        "device_name": torch_module.cuda.get_device_name(0) if torch_module.cuda.is_available() else "",
        "cuda_runtime": getattr(torch_module.version, "cuda", None),
    }


def _max_memory_mib(torch_module: Any) -> int:
    return int(round(torch_module.cuda.max_memory_allocated() / 1024 / 1024))


def _is_within_output_root(path: Path, root: Path) -> bool:
    path_parts = Path(path).parts
    root_parts = Path(root).parts
    return len(path_parts) >= len(root_parts) and path_parts[: len(root_parts)] == root_parts


def find_missing_modules(module_names: list[str]) -> list[str]:
    missing: list[str] = []
    for module_name in module_names:
        try:
            importlib.import_module(module_name)
        except ModuleNotFoundError:
            missing.append(module_name)
    return missing


def plan_smoke_schedule(*, full_batches: int, max_steps: int) -> list[tuple[int, int]]:
    if full_batches <= 0 or max_steps <= 0:
        return []
    schedule: list[tuple[int, int]] = []
    for step_number in range(1, max_steps + 1):
        batch_index = ((step_number - 1) % full_batches) + 1
        schedule.append((step_number, batch_index))
    return schedule


if __name__ == "__main__":
    raise SystemExit(main())
